#############################################################################################################
#                                                                                                           #
# 为了减少重复配置，本配置文件为此sa-admin的独有配置，更多配置请查看 sa-base 项目中的 sa-base.yaml 通用配置文件。      #
# 其中此文件中配置可以覆盖 sa-base.yaml 中的通用配置，具体实现类请看类：YamlProcessor.java                          #
#                                                                                                           #
#############################################################################################################

# 项目配置: 名称、日志目录
project:
  name: sa-admin
  log-directory: ${localPath:/home}/logs/smart_admin_v3/${project.name}/${spring.profiles.active}

# 项目端口和url根路径
server:
  port: 1024
  servlet:
    context-path: /

# 环境
spring:
  profiles:
    active: '@profiles.active@'
mopga:
  translate:
    url: https://fanyi-api.baidu.com/api/trans/vip/translate
    appId: 20230712001741532
    secret: n5rLbzSf5LIjDHUQVqbx




langchain4j:
  community:
    dashscope:
      chat-model:
        base-url:  https://api.deepseek.com
        model-name: deepseek-chat
        api-key: sk-958d51674c754020b24eefad6a2fb854
      streaming-chat-model:
        base-url:  https://api.deepseek.com
        model-name: deepseek-chat
        api-key: sk-958d51674c754020b24eefad6a2fb854
      embedding-model:
        base-url:  https://api.deepseek.com
        model-name: text-embedding-v4
        api-key: <Your API Key>

